TeamTheGenius/TeamTheGenius_Web

package.json, src/App.tsx, src/components/MobCard.tsx, src/index.css, src/pages/singUp/SignUp.tsx, src/pages/singUp/signUpStyle.css, yarn.lock
- 관심사 항목은 더 좋은 방법을 찾기 위해 비워뒀습니다.
- 라이브러리를 추가했습니다.(formik, react-route-dom, yup)
Related to: #6
회원가입 페이지 생성
-formik, yup으로 유효성 검사 및 form 작성
-tailwind, css 작성
-yup, fomik, react-remote-dom 라이브러리 적용
[관심사 선택사항 기능에 대한 의견제시](https://www.figma.com/file/wB6T8yWhJsRF11FDtTTGIb/%EC%A7%80%EB%8B%88%EC%96%B4%EC%8A%A4%3A-%ED%94%84%EB%A1%9C%ED%86%A0%ED%83%80%EC%9E%85?type=design&node-id=215%3A1344&mode=design&t=jrfehPZsVCLqzkVN-1)
=>  Feat: 회원가입 페이지 작성 중

src/App.tsx, src/pages/Landing/Landing.tsx, src/pages/LogIn/LogIn.tsx
Related to: #10
로그인, 회원가입 라우터 설정하였음
페이지 뒤로가기 누를 시 이동할 페이지를 지정하기 위함
closed #10 
"/" : \<Landing/>
"/login": \<LogIn/>
"/login/signup": \<SignUp/>
=> Feat: 로그인, 회원가입 라우터 설정

package.json, tsconfig.json, vite.config.ts, yarn.lock
Related to: #19
alias 적용함
파일 import 할 때 상대 경로가 '../../../' 이런식으로 길어지는 문제 해결
closed #19 
alias를 적용해 절대 경로를 씀으로써 상대 경로가 길어지는 문제를 해결함
예를 들어
```
import Footer from "../../components/Footer";
import Header from "../../components/Header";
```
```
import Footer from "@components/Footer";
import Header from "@components/Header";
```
이렇게 쓸 수 있습니다.
=> Feat: alias 적용

src/pages/LogIn/LogIn.tsx, src/pages/LogIn/TermsOfService/TermsOfService.tsx
Related to: #21
약관 동의 멘트 추가했습니다.
개인정보 처리방침에 따라 추가하였습니다. 
closed #21 
약관 동의 멘트 추가했습니다.
개인 정보 보호 정책과 서비스 약관은 링크를 연결해야하는데 아직 어떤 링크로 보낼지 정해지지 않아 a 태그로 감싸두기만 했습니다. 추후 링크가 나오면 바로 href에 링크 넣을 예정입니다!
=> Feat: 약관 컴포넌트 완성, 로그인 페이지 완성

index.html, src/index.css, src/pages/LogIn/GoogleButton/GoogleButton.tsx, tailwind.config.js
Related to: #22
폰트 최적화를 진행하였습니다.
폰트가 깜빡 거리는 이슈가 있어 이를 해결하고 사용자 경험을 높이고자 수정했습니다.
closed #22 
가변 다이나믹 서브셋 폰트를 이용하여 Pretendard 폰트 최적화를 진행하였습니다.
노션 트러블 슈팅/폰트 최적화에 최적화 과정을 정리해두었습니다!
=> Feat: pretendard variable 폰트 최적화

src/components/Error/ErrorHeader/ErrorHeader.tsx, src/components/Interest/InterestButton/InterestBtn.tsx, src/components/Interest/InterestHeader/InterestHeader.tsx, src/components/Interest/InterestModalHeader/InterestModalHeader.tsx, src/components/Interest/InterestModalInput/InterestModalInput.tsx, src/components/Landing/Comment/Comment.tsx, src/components/LogIn/Comment/Comment.tsx, src/components/LogIn/TermsOfService/TermsOfService.tsx, src/components/Main/UserCircle/UserCircle.tsx, src/components/SignCompleteModal/SignCompleteHeader/SignCompleteHeader.tsx, src/components/SignUp/SignUpHeader/SignUpHeader.tsx, src/components/SignUp/SignUpInput/SignUpInput.tsx, src/components/common/Button.tsx, src/index.css
font code 리팩토링
Closed #62
font-pretendard 전체 적용 후 중복되는 css를 삭제했습니다.
=> Refactor: font-pretendard 전체 적용 후 중복된 코드 삭제

.github/ISSUE_TEMPLATE/refactor-template.md
리팩토링 위한 이슈 템플릿 생성
리팩토링시 사용할 수 있는 이슈 템플릿입니다.
=> Docs: 코드 리팩토링 이슈를 위한 템플릿입니다.

index.html, src/index.css, tailwind.config.js
Related to: #78
폰트를 변경하였습니다.
closed #78 
- SCoreDream폰트 굵기 100~900에 대해 폰트를 설정하였습니다.
=> Feat: SCcoreDream 폰트 세팅

src/components/common/LoginMobCard.tsx, src/components/common/MobCard.tsx, src/index.css, src/pages/Interest/Interest.tsx, src/pages/Landing/Landing.tsx, src/pages/LogIn/LogIn.tsx, src/pages/signUp/SignUp.tsx
main에 쓰일 공통 컴포넌트와 가입과 로그인에 쓰일 공통 컴포넌트 분리
closed #85 
가입과 로그인 페이지에 사용할 공통 컴포넌트와 메인에 쓰일 공통 컴포넌트 분리
로그인 페이지에 UI가 393px 고정되어있는데 따로 이유가 있으신가요?
=> Refactor: loginMobCard 생성

src/App.tsx, src/components/Admin/AdminTopic/TopicListComponent/TopicListComponent.tsx, src/components/Landing/Button/Button.tsx, src/components/Main/MainHeader/MainHeader.tsx, src/components/Main/MoreButton/MoreButton.tsx, src/components/Main/Tab/Tab.tsx, src/components/Main/Tabs/Tabs.tsx, src/components/SignUp/SignUpForm/SignUpForm.tsx, src/constants/path.ts, src/pages/Interest/Interest.tsx, src/pages/Main/Home/Home.tsx
Related to: #98
경로를 상수화하였습니다.
코드에서 navigate를 할 때 경로를 한 번 수정할 때 여러 파일을 수정해야 하는 번거로움을 없애기 위해서입니다.
#98 
src/constants/path.ts 파일에 경로를 상수화하였습니다.
=> Refactor: 경로 상수화

src/App.tsx, src/components/Admin/AdminTopic/TopicListComponent/TopicListComponent.tsx, src/components/Landing/Button/Button.tsx, src/components/Main/MainHeader/MainHeader.tsx, src/components/Main/MoreButton/MoreButton.tsx, src/components/Main/Tab/Tab.tsx, src/components/Main/Tabs/Tabs.tsx, src/components/SignUp/SignUpForm/SignUpForm.tsx, src/constants/path.ts, src/pages/Interest/Interest.tsx, src/pages/Main/Home/Home.tsx, src/pages/Main/Main.tsx, src/pages/Main/Search/Search.tsx
검색 페이지 UI 완성하였습니다.
#102 
- 기존에 만들어 둔 FilterButton 컴포넌트, FilterButtons 컴포넌트, VerticalChallengeItems 컴포넌트를 사용해 만들었습니다.
=> Feature/102 search page UI

src/apis/getAdminListApi.ts, src/apis/postAdminTopicApi.ts, src/apis/postJWTApi.ts, src/apis/postSignUpApi.ts, src/components/Admin/AdminTopic/TopicCreateModal/TopicCreateModal.tsx, src/components/Admin/AdminTopic/TopicListComponent/TopicListComponent.tsx, src/constants/path.ts, src/pages/Admin/AdminTopic/AdminTopic.tsx, src/pages/MyChallenge/MyChallenge.tsx
#110 어드민 api 연동 - 미안성 
토픽 생성, 리스트 요청 api 확인
이미지 생성 api 테스트 중
JWT 로그인 작업 후 작업 예정
=> feat: 어드민 api 연동  - 미완성

src/App.tsx, src/apis/postJWTApi.ts, src/apis/postSignUpApi.ts, src/components/Interest/InterestButton/InterestBtn.tsx, src/components/Interest/InterestHeader/InterestHeader.tsx, src/components/SignUp/SignUpForm/SignUpForm.tsx, src/components/SignUp/SignUpForm/SignUpName/SignUpName.tsx, src/constants/path.ts, src/pages/Auth/Auth.tsx, src/pages/Interest/Interest.tsx, src/pages/LogIn/LogIn.tsx, src/pages/signUp/signUpStyle.css
로그인 jwt api 연동 및 가입페이지 UI 수정
closed #116 #126 #
- 로그인 jwt api 연동 
- 가입페이지(signUp, interest) UI 수정
=> 로그인 jwt api 연동 및 가입페이지 UI 수정

src/App.tsx, src/assets/icon/back-icon.svg, src/components/common/ChallengeItem/ChallengeItem.tsx, src/components/common/Header/Header.tsx, src/constants/path.ts, src/pages/MyPage/InterestChallenge/InterestChallenge.tsx
Related to: #139
- header 공통 컴포넌트
- challengeItem 컴포넌트에 하트 추가
- 관심 목록 리스트 컴포넌트
- 관심 목록 페이지 UI 완성
close #139 
- header 공통 컴포넌트
- challengeItem 컴포넌트에 하트 추가
- 관심 목록 리스트 컴포넌트
- 관심 목록 페이지 UI 완성
=> Feat: 관심 목록 페이지 UI 완성

src/components/common/BottomNav/BottomNav.tsx, src/components/common/VerticalChallengeItems/VerticalChallengeItems.tsx, src/constants/path.ts
Related to: #140
- 하단 네비게이션 버그 발생하여 수정
#140 
하단 네비게이션 버그 수정
해당 url과 현재 url이 일치할 때만 하단 네비게이션이 활성화되도록 하였는데 뭔가..적절한 방법이 아닌 것 같습니다.
더 좋은 방법이 있을까요?
=> Feat: 하단 네비게이션 버그 수정

src/App.tsx, src/apis/postJWTApi.ts, src/components/Certification/Certification/ChallengeDetailLinkButton/ChallengeDetailLinkButton.tsx, src/components/Certification/Certification/ChallengeImage/ChallengeImage.tsx, src/components/Certification/Certification/ChallengeInformation/ChallengeInformation.tsx, src/components/Certification/Certification/ChallengePeriod/ChallengePeriod.tsx, src/components/Certification/Certification/ChallengeReward/ChallengeReward.tsx, src/components/Certification/Certification/ChallengeTitle/ChallengeTitle.tsx, src/components/Certification/Certification/Information/Information.tsx, src/components/Certification/Certification/Line/Line.tsx, src/components/Certification/Certification/NextArrowIcon/NextArrowIcon.tsx, src/components/Certification/Certification/ParticipantCount/ParticipantCount.tsx, src/components/Certification/Certification/Tab/Tab.tsx, src/components/Certification/Certification/Tabs/Tabs.tsx, src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx, src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx, src/components/common/DynamicBackIcon/DynamicBackIcon.tsx, src/components/common/VerticalChallengeItems/VerticalChallengeItems.tsx, src/constants/path.ts, src/pages/Auth/Auth.tsx, src/pages/Certification/Certification/Certification.tsx, src/pages/Certification/MyCurrentCertification/MyCurrentCertification.tsx, src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx, src/pages/ChallengeDetail/ChallengeDetail.tsx, src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx, src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx, src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
Related to: #145
인증페이지-인증페이지 UI
#145 
- 경로: "/certification
- ChallengeImage 컴포넌트
- ChallengeInformation 컴포넌트
- ChallengePeriod 컴포넌트
- ChallengeReward 컴포넌트
- ChallengeTitle 컴포넌트
- Line 컴포넌트
- ParticipantCount 컴포넌트
- Tab , Tabs 컴포넌트
- 나의 인증 현황(/certification/:id/my-current), 참가자 인증 현황(/certification/:id/others-current) outlet
- ChallengeDetailLinkButton 컴포넌트
위의 모바일 뷰에서 챌린지 상세보기 버튼이 저기로 간 것은 디자인이랑 다르게 구현한 것이 아닌  flex-wrap을 적용했기 때문입니다!
=> Feat: 인증페이지 - 인증페이지 UI 완성

src/App.tsx, src/components/MyPage/MyPage/SettingButton/SettingButton.tsx, src/components/MyPage/SettingMenu/LinkButton/LinkButton.tsx, src/components/MyPage/SettingMenu/Title/Title.tsx, src/components/common/BottomNav/BottomNav.tsx, src/constants/path.ts, src/pages/MyPage/ProfileSetting/ProfileSetting.tsx, src/pages/MyPage/SettingMenu/SettingMenu.tsx
Related to: #152
마이페이지 - 설정 메뉴 페이지 UI 완성
#152 
- Header 공통 컴포넌트 사용하여 Header 완성
- Title 컴포넌트
- LinkButton 컴포넌트
- 공통 컴포넌트 Line 사용
- SettingMenu 페이지 완성
=> Feat: 마이페이지 - 설정 메뉴 페이지 UI 완성

src/App.tsx, src/components/Certification/MyAllCurrentCertification/MyAllCertificationResult/MyAllCertificationResult.tsx, src/components/Certification/MyAllCurrentCertification/MyProfile/MyProfile.tsx, src/components/Certification/MyCurrentCertification/MyAllCertificationLinkButton/MyAllCertificationLinkButton.tsx, src/components/Certification/MyCurrentCertification/ThisWeekCertification/ThisWeekCertification.tsx, src/components/MyPage/MyPage/MyProfile/MyProfile.tsx, src/components/common/Profile/Profile.tsx, src/constants/path.ts, src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx
Related to: #156
인증 페이지 - 나의 전체 인증 현황 UI 완성
close #156 
- 헤더 공통 컴포넌트 사용
- 프로필 공통 컴포넌트 사용
- CertificationResult 공통 컴포넌트 사용
- 나의 인증 현황 페이지 완성
배치 관련해서 디자이너 소희님이랑 타협한 UI로 진행하였습니다!
=> Feat: 인증 페이지 - 나의 인증 현황 UI 완성

src/components/Certification/MyAllCurrentCertification/MyProfile/MyProfile.tsx, src/components/Certification/MyCurrentCertification/ThisWeekCertification/ThisWeekCertification.tsx, src/components/Certification/OthersCurrentCertification/OthersAllCertificationLinkButton/OthersAllCertificationLinkButton.tsx, src/components/Certification/OthersCurrentCertification/OthersProfile/OthersProfile.tsx, src/components/Certification/OthersCurrentCertification/ThisWeekCertification/ThisWeekCertification.tsx, src/components/MyPage/MyPage/LinkButtons/LinkButtons.tsx, src/components/MyPage/MyPage/MyProfile/MyProfile.tsx, src/components/common/Header/Header.tsx, src/components/common/Profile/Profile.tsx, src/constants/path.ts, src/data/myCertificationResultData.ts, src/data/othersCertificationResultData.ts, src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx, src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
인증페이지 - 참가자 인증 현황 UI 완성
close #158 
- OthersProfile 컴포넌트
- OthersAllCertificationLinkButton 컴포넌트
- ThisWeekCertification 컴포넌트
- OthersCurrentCertification 페이지 컴포넌트 완성
=> Feature/158 participant current certification UI

src/App.tsx, src/components/Certification/OthersAllCurrentCertification/OthersAllCertificationResult/OthersAllCertificationResult.tsx, src/components/Certification/OthersAllCurrentCertification/OthersProfile/OthersProfile.tsx, src/components/Certification/OthersAllCurrentCertification/ReportButton/ReportButton.tsx, src/components/Certification/OthersCurrentCertification/OthersAllCertificationLinkButton/OthersAllCertificationLinkButton.tsx, src/components/Certification/OthersCurrentCertification/ThisWeekCertification/ThisWeekCertification.tsx, src/components/common/Profile/Profile.tsx, src/constants/path.ts, src/data/othersCertificationResultData.ts, src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx, src/pages/Certification/OthersAllCurrentCertification/OthersAllCurrentCertification.tsx, src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
Related to: #160
인증페이지 - 참가자 전체 인증 현황 UI 완성
#160 
- 헤더 컴포넌트
- 신고하기 버튼 컴포넌트
- OthersProfile 컴포넌트
- OthersAllCertificationResult 컴포넌트
- OthersAllCurrentCertification 페이지 완성
=> Feat: 인증 페이지 - 참가자 전체 인증 현황 UI 완성

package.json, src/apis/getLatestChallenge.ts, src/apis/getPopularChallenge.ts, src/apis/getRecommendedChallenge.ts, src/apis/postJWTApi.ts, src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx, src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx, src/components/common/ChallengeItem/ChallengeItem.tsx, src/components/common/VerticalChallengeItems/VerticalChallengeItems.tsx, src/hooks/useInfiniteScroll.ts, src/pages/Home/NewChallenge/NewChallenge.tsx, src/pages/Home/PopularChallenge/PopularChallenge.tsx, src/pages/Home/SuggestionChallenge/SuggestionChallenge.tsx, src/utils/makeBase64IncodedImage.ts, yarn.lock
Related to: #142
- 홈화면 무한 스크롤 적용했습니다
#142 
홈 화면 무한 스크롤 적용했습니다.
요소를 height가 꽉차지 않도록 가져오면 스크롤이 생기지 않아 무한스크롤이 안됩니다. 이 부분 해결해야 할 것 같습니다.
=> Feat: 홈 화면 api 연결

src/App.tsx, src/components/MyPage/ServiceWithdraw/ReasonChoice/ReasonChoice.tsx, src/components/MyPage/ServiceWithdraw/Title/Title.tsx, src/components/MyPage/ServiceWithdraw/UnderLine/UnderLine.tsx, src/components/MyPage/ServiceWithdraw/WithdrawButton/WithdrawButton.tsx, src/components/common/BottomNav/BottomNav.tsx, src/constants/path.ts, src/pages/MyPage/GithubToken/GithubToken.tsx, src/pages/MyPage/InterestChallenge/InterestChallenge.tsx, src/pages/MyPage/ServiceWithdraw/ServiceWithdraw.tsx, src/pages/MyPage/SettingMenu/SettingMenu.tsx
Related to: #155
마이페이지 - 탈퇴페이지 UI 완성하였습니다.
#155 
- path: serviceWithdrawal
- Header 공통 컴포넌트 사용
- Title 컴포넌트
- ReasonChoice 컴포넌트
- WithdrawButton 컴포넌트
- ServiceWithdraw 페이지 컴포넌트 완성
=> Feat: 마이페이지 탈퇴하기 UI 완성

src/apis/postGithubTokenRegi.ts, src/components/GithubToken/GithubTokenInput.tsx
Resolves: #183
close #183   
- github token api 연동 완료
=> feat: github api Test 완료

src/App.tsx, src/components/Main/MyChallenge/MyChallengeHeader/MyChallengeHeader.tsx, src/components/Main/MyChallenge/MyChallengeLabel/MyChallengeLabel.tsx, src/components/Main/MyChallenge/MyChallengeModal/MyChallengeModal.tsx, src/components/common/Modal/Modal.tsx, src/constants/path.ts, src/hooks/useModal.ts, src/index.css, src/pages/Main/Main.tsx, src/pages/MyChallenge/MyChallenge.tsx, src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx, src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx, src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx, src/utils/breakLine.tsx
수령 모달 완성, 라우팅 이슈 해결, 시작전 탭 깨진 UI 복구, 모달 공통컴포넌트화
#189 
- 수령 모달 완성
- 라우팅 이슈 해결
- 시작전 탭 깨진 UI 복구
- 모달 공통컴포넌트화
최상단에서 커스텀hook 모달 로직 불러오고 하위 컴포넌트에서 setModal, closeModal, openModal 이용하면 됩니다.
setModal은 Modal 컴포넌트 지정, closeModal은 모달 닫기, openModal은 모달 열기입니다. 이해 안되시는 점 있으면 언제든 알려주세용
=> Feature/189 my challenge change UI

src/components/common/BottomButton/BottomButton.tsx, src/components/common/BottomNav/BottomNav.tsx, src/pages/MyPage/UserInfoEdit/UserInfoEdit.tsx, src/pages/Payments/Fail/Fail.tsx, src/pages/Payments/Payments.tsx, src/pages/Payments/Success/Success.tsx
Resolve: #187 #185
closed #185 #187 
- UserEdit 프로필 사진 공통 컴포넌트로 변경
- BottomButton 공통 컴포넌트 수정 및 적용
- BottomNav 공통 컴포넌트 불필요 코드 제거
=> refactor: bottomNav 공통 컴포넌트 수정 및 적용 user profile 공통 컴포넌트로 변경

src/App.tsx, src/apis/getSearchedChallengeItem.ts, src/components/Search/FilterButton/FilterButton.tsx, src/components/Search/FilterButtons/FilterButtons.tsx, src/components/common/ChallengeItem/ChallengeItem.tsx, src/constants/path.ts, src/pages/Home/NewChallenge/NewChallenge.tsx, src/pages/Home/PopularChallenge/PopularChallenge.tsx, src/pages/Home/Search/ActivitySearch/ActivitySearch.tsx, src/pages/Home/Search/AllSearch/AllSearch.tsx, src/pages/Home/Search/DoneSearch/DoneSearch.tsx, src/pages/Home/Search/PreActivitySearch/PreActivitySearch.tsx, src/pages/Home/Search/Search.tsx
Related to: #170
검색 api 연결
#170 
- 검색 api 연결
- 무한 스크롤 적용
다른 무한스크롤이 있는 페이지와 마찬가지로 요소의 height가 브라우저보다 작으면 스크롤이 생기지 않아 무한스크롤이 안됩니다. 따로 이슈 만들어서 버그 해결하겠습니다.
=> Feat: 검색 api 연결

src/apis/getCertificationInformation .ts, src/apis/getCertificationInstanceDetail .ts, src/apis/getCertificationWeek.ts, src/components/Certification/Certification/ChallengeInformation/ChallengeInformation.tsx, src/components/Certification/MyCurrentCertification/CurrentAchivementRate/CurrentAchivementRate.tsx, src/components/Certification/MyCurrentCertification/MyCertificationSummary/MyCertificationSummary.tsx, src/components/Certification/MyCurrentCertification/MyRepository/MyRepository.tsx, src/components/Certification/MyCurrentCertification/ThisWeekCertification/ThisWeekCertification.tsx, src/components/Home/HorizontalScroll/HorizontalScroll.tsx, src/components/Home/PopularChallengeItems/PopularChallengeItems.tsx, src/components/Home/SuggestionChallengeItems/SuggestionChallengeItems.tsx, src/components/common/CertificationResult/CertificationResult.tsx, src/data/myCertificationResultData.ts, src/pages/Certification/Certification/Certification.tsx, src/pages/Certification/MyCurrentCertification/MyCurrentCertification.tsx, src/utils/getIsToday.ts
인증페이지 api 연결 절반 완성
#166 
- 챌린지 상세 정보 조회
- 사용자의 챌린지 현황 조회
- 특정 사용자의 일주일 인증 현황 조회
- 인증페이지에 대한 남은 api는 백엔드 부분 수정 후 연결하겠습니다.
=> Feature/166 certification page api - 1/2

src/apis/getMyChallengePreActivity.ts, src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
Related to: #198
마이챌린지 시작전 api 연결
#198 
마이챌린지 시작전 api 연결
=> Feat: 마이챌린지 - 시작 전 api 연결

src/apis/getMyChallengeActivity.ts, src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
Related to: #202
마이챌린지 - 진행중 api 연결
#202 
- 마이챌린지 - 진행중 api 연결
- 인증 패스권은 UI 구현하시면 로직 구현하겠습니다.
=> Feat: 마이챌린지 - 진행중 api 연결

src/apis/getMyChallengeDone.ts, src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
Related to: #204
마이챌린지 - 완료 api 연결
#204 
마이챌린지 - 완료 api 연결
=> Feat: 마이챌린지 - 완료 api 연결

src/apis/getMyChallengeDoneReward.ts, src/components/Main/MyChallenge/MyChallengeModal/MyChallengeModal.tsx, src/pages/MyChallenge/MyChallengeComplete/MyChallengeComplete.tsx
Related to: #206
마이챌린지 완료탭 보상 api 연결
#206 
- 마이챌린지 완료탭 보상 api 연결
=> Feat: 마이챌린지 완료탭 보상 api 연결

src/App.tsx, src/apis/getGithubTokenApi.ts, src/apis/getRepoVertifyApi.ts, src/apis/postChallengeRepoRegiApi.ts, src/apis/postGithubTokenRegi.ts, src/components/GitPullReqConnect/GitTokenCheckIcon/GitTokenCheckIcon.tsx, src/components/GitPullReqConnect/Label/Label.tsx, src/components/GitPullReqConnect/PullReq/PullReq.tsx, src/components/GitPullReqConnect/Repo/Repo.tsx, src/components/GithubToken/GithubTokenInput.tsx, src/pages/ChallengeDetail/GitPullReqConnect/GitPullReqConnect.tsx
깃허브 토큰 등록 시 리렌더링이 되게 했습니다.
중복된 컴포넌트 공통 컴포넌트화 했습니다.
참가하기 버튼에 useNavigate 수정했습니다.
closed #213 
- 깃허브 토큰 등록 시 리렌더링
- 중복된 컴포넌트 공통 컴포넌트화
- 참가하기 버튼 useNavigate 오류 수정
- repoState가 api 성공 시 담기도록 수정
=> refactor: #199에서 중복된 컴퍼넌트 공통 컴포넌트 화 및 깃허브 토큰 등록 시 데이터 캐시 업데이트

src/components/Main/MyChallenge/MyChallengeLabel/MyChallengeLabel.tsx, src/components/Main/MyChallenge/MyChallengePass/MyChallengePassItem.tsx, src/components/Main/MyChallenge/MyChallengeTitle/MyChallengeTitle.tsx, src/components/Main/MyChallenge/MyChallengeWrap/MyChallengeWrap.tsx, src/components/common/Modal/Modal.tsx, src/pages/MyChallenge/MyChallengeProgress/MyChallengePassModal/MyChallengePassModal.tsx, src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
closed #222   
- 인증 패스 UI
- 클릭 시 인증 패스 사용 모달 UI
- 모달 공통 컴포넌트 수정
- 인증 버튼 tailwind 수정
기존 컴포넌트 임의로 수정한 것 있습니다.
Modal.tsx에 absolute를  fixed로 변경했습니다.
MyChallengeLabel.tsx에 div에 되어있던 크기지정을 button태그로 옮겼습니다.
=> feat: myChallenge 인증패스 버튼 UI 및 모달 UI 추가했습니다.

src/apis/getSearchedChallengeItem.ts, src/components/Home/HomeHeader/HomeHeader.tsx, src/components/common/BottomNav/BottomNav.tsx, src/pages/Home/Search/ActivitySearch/ActivitySearch.tsx, src/pages/Home/Search/AllSearch/AllSearch.tsx, src/pages/Home/Search/DoneSearch/DoneSearch.tsx, src/pages/Home/Search/PreActivitySearch/PreActivitySearch.tsx, src/pages/Home/Search/Search.tsx, src/pages/Main/Main.tsx
Related to: 208
- 검색 페이지 오류 해결
#208 
- 하단 네비게이션 "홈" 활성화 안됨
-  검색(엔터) 누르면 /main/home/search로 이동함.. /main/home/어딘가.. 에서 검색하면 /main/home/search/all로 이동하고 /main/home/search/어딘가.. 에서 검색하면 그대로 있기
- title(keyword) 추가
- 필터 바꿔도 검색 단어 그대로
- useInfinite로 무한스크롤 적용
=> Fix: 검색 페이지 버그 해결

src/components/Main/MyChallenge/MyChallengeLabel/MyChallengeLabel.tsx, src/components/Main/MyChallenge/MyChallengePass/MyChallengePassItem.tsx, src/components/Main/MyChallenge/MyChallengeTitle/MyChallengeTitle.tsx, src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx
=> Feature/222 feat mychallenge pass UI

src/apis/deleteServiceWithdraw.ts, src/components/MyPage/ServiceWithdraw/WithdrawButton/WithdrawButton.tsx
Related to: #231
탈퇴 api 이유 추가
#231 
탈퇴 api 이유 추가
=> Feat: 탈퇴 api 이유 추가

src/apis/postUserProfile.ts, src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx, src/pages/Certification/OthersAllCurrentCertification/OthersAllCurrentCertification.tsx, src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
Related to: #234
인증 상세페이지 프로필 api 연결
#234 
인증 상세페이지 프로필 api 연결
- 인증 상세 api랑 프로필 api가 따로 있어서 백엔드에서 브랜치 합병 후,  잘 동작하는지 확인해봐야할 것 같습니다! 
- 쿼리키도 잘못하면 겹칠 위험성이 있는 것 같아서 상수화시키면 어떨까 싶기도 한데..어떠신가요??
=> Feat: 인증 상세페이지 프로필 api 연결

src/apis/postAuthLogout.ts, src/pages/Auth/Auth.tsx, src/pages/LogIn/LogIn.tsx, src/pages/MyPage/SettingMenu/SettingMenu.tsx
Related to: #246
- 로그아웃 로직 오류 수정
#246 
auth 페이지에서 
1. identifier가 저장돼있는 경우( 예: 로그인 해서 로그아웃 안 한 경우) JWT 요청
2. identifier가 저장돼있지 않는 경우( 예: 로그인 후 로그인 한 경우) identifier 저장 후 JWT 요청
3. 회원가입 이동 로직 삭제
=> Fix: 로그아웃 로직 오류 수정

src/apis/postLikeChallenge.ts, src/components/ChallengeDetail/Bottom/Bottom.tsx, src/pages/ChallengeDetail/ChallengeDetail.tsx, src/pages/MyPage/InterestChallenge/InterestChallenge.tsx
Related to: #243
- 좋아요 토글 연결
#243 
- 좋아요 등록 api 연결
- 좋아요 취소 api 연결
- 좋아요 상태 연결
=> Feat: 좋아요 토글 연결

src/assets/icon/bordered-blue-right-arrow-icon.svg, src/components/Certification/CertificationModal/CertificationPRLinkModal/CertificationPRLinkModal.css, src/components/Certification/CertificationModal/CertificationPRLinkModal/CertificationPRLinkModal.tsx, src/components/Certification/ThisWeekCertification/ThisWeekCertification.tsx, src/components/Certification/TotalCertification/TotalCertification.tsx, src/components/common/CertificationResult/CertificationResult.tsx, src/hooks/useModal.ts
인증페이지 UI 추가/변경
#262 
- pass UI 추가
- pr 링크 모달 UI 변경
- 화면이 작아진 상태에서 캡처를 해서 피그마 UI보다 모달의 width가 줄어들었습니다..!
=> Feature/262 certification UI add/edit

src/components/Certification/MyCurrentCertification/PRTemplate/PRTemplate.tsx, src/pages/Certification/MyCurrentCertification/MyCurrentCertification.tsx
Related to: #260
- 인증 페이지 - UUID api 연결
#260 
- 인증 페이지 - UUID api 연결
=> Feat 인증페이지 UUID api 연결

src/apis/getMyChallengeDoneReward.ts
Related to: #280
- 보상 api 연결 오류 해결
#280 
- 보상 api 연결 오류 해결
=> Bugfix: 보상 api 연결 오류 해결

src/components/Certification/TotalCertification/TotalCertification.tsx
Related to: #282
- 전체 인증 현황 조회 예외 처리
#282 
- 백엔드에서 잘못된 데이터를 주어 array length 에러가 나더라도 빈 화면을 띄워주지 않도록 array length 예외처리를 하였습니다.
=> Bugfix: 전체 인증 현황 조회 array length 예외 처리

src/components/MyPage/MyPage/LinkButtons/LinkButtons.tsx, src/pages/MyPage/InterestChallenge/InterestChallenge.tsx, src/pages/MyPage/InterestEdit/InterestEdit.tsx
Related to: #284
- 마이페이지 헤더, 링크 라벨 불일치 현상 해결
#284 
1. 관심 목록 -> 좋아요 목록
2. 헤더 관심사 수정 -> 좋아요 목록
3. 헤더 관심 목록 -> 관심사 수정
=> Bugfix: 마이페이지 헤더 불일치, 링크 라벨 불일치 해결

src/components/GithubToken/GithubTokenInput.tsx
closed #276 
- github 토큰 ui 수정
=> refacotr: github token ui 수정

src/components/Admin/AdminTopic/TopicCreateModal/TopicCreateModal.tsx, src/components/Admin/AdminTopic/TopicListComponent/TopicListComponent.tsx, src/components/Error/ErrorHeader/ErrorHeader.tsx, src/pages/Admin/AdminInstance/AdminInstance.tsx, src/pages/Admin/AdminTopic/AdminTopic.tsx, src/pages/Auth/Auth.tsx, src/pages/error/Error.tsx
cloesd #277   
- admin 페이지 접속 시 postJwt api로 admin 확인
admin page에 접속할 때 postJwt로 admin 확인하는 식으로 했는데 더 좋은 방법 있을까요?
=> feat: 어드민 페이지 보안

src/App.tsx, src/apis/axios/AxiosNavigation.tsx, src/components/Route/PrivateRoute/PrivateRoute.tsx, src/pages/Auth/Auth.tsx, src/pages/error/Error.tsx
Related to: #292
jwt 유효 않을 때 처리
#292 
jwt 유효 않을 때 처리
공통적으로 적용되는 에러 핸들은 AxiosNavigation 파일안에서 처리하면 됩니닷, 원래는 error boundary로 시도하였으나 error boundary가 캐치하지 못하는 것들이 꽤 있어서 좀 불편하더라구요.. 그래서 axios의 interceptor를 사용하였습니다. 더 좋은 방법이 있을지 생각해보면 좋을 것 같아용
=> Fix: jwt 유효 않을 때 처리

src/components/common/NickNameInput/NickNameInput.tsx
=> refactor: state 오류 수정

src/apis/postTodayCertification.ts, src/components/Certification/CertificationModal/CertificationFailModal/CertificationFailModal.tsx, src/pages/MyChallenge/MyChallengeProgress/MyChallengeProgress.tsx, src/pages/MyChallenge/MyChallengeStart/MyChallengeStart.tsx
Related to: #294
인증 갱신 실패 시 모달 띄우기
#294 
인증 갱신 실패 시 모달 띄우기
=> Feat: 인증 갱신 실패 시 모달 띄우기

src/components/Certification/MyAllCurrentCertification/MyProfile/MyProfile.tsx, src/components/Certification/OthersCurrentCertification/OthersAllCertificationLinkButton/OthersAllCertificationLinkButton.tsx, src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
Related to: #303
참가자 인증 내역 조회 시 버그 해결
#303 
참가자 인증 내역 조회 시 버그 해결
=> Fix: 참가자 인증 내역 조회 시 버그 해결

src/components/MyPage/MyPage/MyProfile/MyProfile.tsx, src/pages/Certification/MyAllCurrentCertification/MyAllCurrentCertification.tsx, src/pages/Certification/OthersAllCurrentCertification/OthersAllCurrentCertification.tsx, src/pages/Certification/OthersCurrentCertification/OthersCurrentCertification.tsx
Related to: #314
- 프로필 기본 이미지 설정
#314 
- 서버에서 이미지 none으로 보낼 시 프로필 기본 이미지 띄우기
=> Feat: 프로필 기본 이미지 설정

src/components/Main/MyChallenge/MyChallengeHeader/MyChallengeHeader.tsx, src/components/common/MainHeader/MainHeader.tsx, src/pages/MyChallenge/MyChallenge.tsx, src/pages/MyPage/MyPage/MyPage.tsx, src/pages/Shop/Shop.tsx
- header fix 적용, 배경색 적용
- alram 아이콘 숨김
=> refactor: header 수정

src/components/common/MainHeader/MainHeader.tsx
헤더 z-index 높이기
- 헤더 z-index 높이기
=> Fix: 헤더 z-index 높이기

src/apis/getPullRequestVerifyApi.ts, src/components/GitPullReqConnect/GitPullReqModal/GitPullReqModal.tsx, src/components/GitPullReqConnect/PullReq/PullReq.tsx, src/components/common/BottomNav/bottomNavStyle.css, src/pages/ChallengeDetail/GitPullReqConnect/GitPullReqConnect.tsx
closed  #329
- pr 모달 수정, res 200일 시 pr이 있다는 메세지 띄우기
=> bug: pr 확인 모달 정상 작동 안되던 현상 수정

src/apis/getCheckNicknameApi.ts, src/components/Common/BottomNav/bottomNavStyle.css, src/components/Common/NickNameInput/NickNameInput.tsx, src/components/SignUp/SignUpForm/SignUpForm.tsx, src/components/SignUp/SignUpForm/SignUpModal/SignUpModal.tsx, src/components/common/NickNameInput/NickNameInput.tsx, src/pages/MyPage/UserInfoEdit/UserInfoEdit.tsx
- 닉네임 중복확인 유효성 검사 버그 수정
- 모달 추가
=> bug: nickName check 수정

src/App.tsx, src/components/Error/PrivateRouteErrorFallback/PrivateRouteErrorFallback.tsx, src/components/Route/PrivateRoute/PrivateRoute.tsx
에러 컴포넌트 계속 존재하는 현상 해결
>>
>> Related to: #335
- 에러 컴포넌트 안사라지는 문제 해결
#335 
에러 컴포넌트 안사라지는 문제 해결
해결은 하였지만 완벽히 된 것이 아니라 좀 더 알아볼 필요가 있을 것 같습니다.
=> Bugfix: jwt 만료 발생 시 에러 컴포넌트 안 사라짐

vercel.json
=> Fix: 배포 404오류 해결

package.json, src/apis/axios/axios.ts, src/apis/postPaymentSuccess.ts, src/setupProxy.js
=> Fix: 서버 url 변경

package.json, src/apis/axios/axios.ts, src/apis/postPaymentSuccess.ts, src/components/LogIn/GithubLoginButton/index.tsx, src/setupProxy.js
=> Feat: 서버 url 변경

src/components/ChallengeDetail/Image/Image.tsx, src/components/Common/MainHeader/MainHeader.tsx, src/components/Home/HomeHeader/HomeHeader.tsx, src/components/MyPage/MyPage/MyPoint/MyPoint.tsx, src/components/common/MainHeader/MainHeader.tsx, src/layout/HomeLayout/HomeLayout.tsx, src/pages/Home/Search/Search.tsx, src/pages/Shop/Shop.tsx, tailwind.config.js
Related to: #344
로고 깜빡임 문제 해결
#344 
로고 깜빡임 문제 해결
=> Fix: 로고 깜빡임 문제 해결

package.json, src/App.tsx, src/apis/axios/axios.ts, src/apis/postPaymentSuccess.ts, src/components/Error/PrivateRouteErrorFallback/PrivateRouteErrorFallback.tsx, src/components/LogIn/GithubLoginButton/index.tsx, src/components/Route/PrivateRoute/PrivateRoute.tsx, src/setupProxy.js
Related to: #346
에러 컴포넌트 안사라지는 문제 해결
#346 
에러 컴포넌트 안사라지는 문제 해결
에러 컴포넌트 보완하는 코드는 다른 브랜치 생성 후 작업하겠습니다!
=> Fix: 에러 컴포넌트 안사라지는 문제 해결

src/components/Shop/ShopModal/ShopTestModal/ShopTestModal.tsx, src/pages/Shop/Shop.tsx
=> feature: payments 개발 중 안내 모달
